version: '3.8'

services:
  db:
    image: postgres:16
    container_name: postgres_db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5433:5432"  
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

  web:
    build: .
    container_name: flask_app
    command: flask run --host=0.0.0.0 --port=80
    environment:
      FLASK_APP: app/main.py
      FLASK_ENV: production  
      SECRET_KEY: ${SECRET_KEY}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_PORT: 5432
      DB_HOST: db
    ports:
      - "5001:80"
    depends_on:
      - db
    networks:
      - backend

networks:
  backend:

volumes:
  postgres_data:
